---
title: "Team contract"
author: "ACE: Austin, Chenemi, Evan"
output: github_document
---


### What are our team goals for this project?
* Have fun
* Communicate big problems in ES with easy to understand visual data graphics
* Refine our skills using the tidyverse and dplyr packages
* Develop skills making animated/interactive plots 
* Connect data visualizations to science communication, specifically as an educational tool (Chenemi)
* Produce a graph in rayshader (Austin) 

### What do we want to accomplish?
* Communicate big problems in ES with easy to understand visual data graphics
* Build connections between geology and environmental science 
* What skills do we want to develop or refine?
* Interpretation and visualization for the general public

## Expectations:
### What do we expect of one another regarding attendance at meetings, participation, frequency of communication, quality of work, etc.?
* We should try to communicate ahead of time when things are not going well or if we anticipate events that might take up time.
* Being aware of deadlines
* Give thoughtful analysis to each other’s ideas.
* We aim for success! High quality work is THE VIBE

## Policies & Procedures:
### What rules can we agree on to help us meet our goals and expectations?
* Divide the work equally
* Check in or meet at least once a week
* Give feedback on work that is already done (leave comments)

## Consequences:
### How will we address non-performance regarding these goals, expectations, policies and procedures?
* No cookies before bedtime 
* A member who is not equally contributing to the project will first be spoken to within the group, and if no changes are made, appropriate disciplinary action will be taken. 

## Ideas for project:
### ES project
* Wildfires
* Glacier melting/sea level rising?
* Carbon production
* Coal/precious metal mining or oil refining?



Geology package: rayshader



## Signed:
Austin Gilbride

Evan Saltman

Chenemi Maji



